[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
license = "GPL3"
default-run = "runtime"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
plugon = { path = "../plugon" }